DROP TABLE IF EXISTS prescriptions  CASCADE;
DROP TABLE IF EXISTS checkups CASCADE;
DROP TABLE IF EXISTS medications CASCADE;
DROP TABLE IF EXISTS patients CASCADE;
DROP TABLE IF EXISTS migrations CASCADE;
